name: CI

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

    - run: npm ci

    - run: npm run lint

    - run: npm run build

    - run: npm test

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

    - run: npm ci

    - uses: andrewaylett/pre-commit-action@a2314cdbad81b709e2e17663985aa03de131403f # v4
      env:
        SKIP: dedupe,lint,test
