name: CI

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

    - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

    - run: npm ci

    - run: npm run lint

    - run: npm run build

    - run: npm test

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

    - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

    - run: npm ci

    - uses: andrewaylett/pre-commit-action@57a149d3daa51e633e2717e245fd508db4682461 # v4
      env:
        SKIP: dedupe,lint,test
